/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.2 */
package com.pip.game.data.quest.pqe;

public interface ParserTreeConstants
{
  public int JJTEXPRESSIONLIST = 0;
  public int JJTEXPRESSION = 1;
  public int JJTEXPR0 = 2;
  public int JJTFUNCTIONCALL = 3;


  public String[] jjtNodeName = {
    "ExpressionList",
    "Expression",
    "Expr0",
    "FunctionCall",
  };
}
/* JavaCC - OriginalChecksum=b7d000fda8e3f1c210b5114bb0aeba19 (do not edit this line) */
