package com.pip.game.editor.util;

import java.io.*;
import java.util.*;

import com.pip.util.PropertiesEx;

/**
 * 程序设置。配置文件是用户HOME目录下的sanguoeditor.properties。
 * @author lighthu
 */
public class Settings {
    /**
     * 当前项目目录。
     */
	public static File workingDir = new File(".");
	/**
	 * 导出Java文件路径。
	 */
	public static File exportClassDir = new File(".");
	/**
	 * BUFF类前缀。
	 */
	public static String buffClassPrefix = "AutoGeneratedBuff_";
	/**
	 * BUFF类包名。
	 */
	public static String buffPackage = "cybertron.core.buff";
	
	/**
     * 任务类前缀。
     */
    public static String questClassPrefix = "AutoGeneratedQuest_";
    /**
     * 任务类包名。
     */
    public static String questPackage = "optimus.quest.auto";
    
    /**
     * AI类前缀。
     */
    public static String aiClassPrefix = "AutoGeneratedAI_";
    /**
     * AI类包名。
     */
    public static String aiPackage = "optimus.ai.auto";
    
    /**
     * 物品使用限制类前缀。
     */
    public static String itemClassPrefix = "AutoGeneratedItem_";
    /**
     * 物品类包名。
     */
    public static String itemPackage = "optimus.item.auto";
	/**
	 * Skill类前缀。
	 */
	public static String skillClassPrefix = "AutoGeneratedSkill_";
	/**
	 * Skill类包名。
	 */
	public static String skillPackage = "cybertron.core.skill";
	public static String propertiesFileName = "sanguoeditor.properties";
	
	/**
	 * 客户端工程目录
	 */
	public static String clientProjDir = "";
	public static String clientProjDir2 = "";
    
	
	public static void loadSetting() {
		String home = System.getProperty("user.home");
		FileInputStream fis = null;
		try {
			PropertiesEx props = new PropertiesEx();
			fis = new FileInputStream(new File(home, propertiesFileName));
			props.load(fis, "GBK");
			workingDir = new File(props.getProperty("working_dir", "."));
			exportClassDir = new File(props.getProperty("export_class_dir", "."));
			buffClassPrefix = props.getProperty("buff_class_prefix", "");
			buffPackage = props.getProperty("buff_package", "");
            skillClassPrefix = props.getProperty("skill_class_prefix", "");
            skillPackage = props.getProperty("skill_package", "");
            questPackage = props.getProperty("quest_package", "");
            aiPackage = props.getProperty("ai_package", "");
            clientProjDir = props.getProperty("client_proj_dir", "");
            clientProjDir2 = props.getProperty("client_proj_dir2", "");
		} catch (IOException e) {
		} finally {
			if (fis != null) {
				try {
					fis.close();
				} catch (IOException e) {
				}
			}
		}
	}

	public static void saveSetting() {
		String home = System.getProperty("user.home");
		FileOutputStream fos = null;
		try {
			fos = new FileOutputStream(new File(home, propertiesFileName));
			PropertiesEx props = new PropertiesEx();
			props.setProperty("working_dir", workingDir.getAbsolutePath());
            props.setProperty("export_class_dir", exportClassDir.getAbsolutePath());
            props.setProperty("buff_class_prefix", buffClassPrefix);
            props.setProperty("buff_package", buffPackage);
            props.setProperty("skill_class_prefix", skillClassPrefix);
            props.setProperty("skill_package", skillPackage);
            props.setProperty("quest_package", questPackage);
            props.setProperty("ai_package", aiPackage);          
            props.setProperty("client_proj_dir", clientProjDir);
            props.setProperty("client_proj_dir2", clientProjDir2);
			props.save(fos, "GBK");
		} catch (IOException e) {
		} finally {
			if (fos != null) {
				try {
					fos.close();
				} catch (IOException e) {
				}
			}
		}
	}
}
